### ISSUE TITLE
Select what version you want to DL or some kind of roll back ability

### ISSUE THREAD

**Issue by Addonman** [WowUp/WowUp#570] opened 2020-12-03 23:22 UTC
**Is your feature request related to a problem? Please describe.**
Yes. On Curse you could select version/release you wanted to DL. Lets say latest version isnt working -how do you go back to version that is working?
**Describe the solution you'd like**
Ability to DL what ever version i want like there was option on CF.

**Describe alternatives you've considered**

**Additional context**

**Comment by jliddev** [comment] 2020-12-10 19:17
Duplicate of #16

**Closed by jliddev** 2020-12-10 19:17 UTC
