### ISSUE TITLE
After monitor input switching WoWUp becomes unresponsive.

### ISSUE THREAD

**Issue by Dillonzer** [WowUp/WowUp#531] opened 2020-11-25 16:48 UTC
**Describe the bug**
When switching inputs on one of my monitors (I run 3 monitors) WoWUp will maximise itself and become unresponsive. I then need to right click the taskbar icon to close it, and it then completely closes it regardless of the setting to minimise it after closing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open WoWUp
2. Unplug / Switch Inputs (using an HDMI Switcher) on one of the monitors

**Expected behaviour**
WoWUp does nothing if minimised, otherwise it just moves to another monitor and is responsive.

**Desktop**
 - OS: Windows 10

**Application Info**
- Version 2.0.0

**Comment by jliddev** [comment] 2020-11-25 16:54
Can you upload your log files? from options -> debug -> show log files

**Comment by mnejing** [comment] 2020-11-26 01:35
I'm attaching mine as I've been experiencing the exact same issue. A brief glance through around the times that the input switching (or, in my case, turning off my main monitors and turning on my TV that is also attached to my PC) doesn't show anything interesting, but that's obviously not for me to decide. 

Anyway, a quick workaround I figured out was to right-click on the icon in the system tray and click "Show." This made the client responsive again, without having to restart. 

[main.log](https://github.com/WowUp/WowUp/files/5599954/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5599955/renderer.log)

**Comment by thettenhausen** [comment] 2020-11-26 14:36
I notice the same behaviour, but have always attributed it to the PC going to sleep (I use my monitor for my work laptop and personal gaming PC, so it happens when I switch). Attaching my logs for an additional data point.
[main.log](https://github.com/WowUp/WowUp/files/5603575/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5603576/renderer.log)

**Comment by jliddev** [comment] 2020-11-26 15:48
Will take another pass at the window resuming code, its kind of a guessing game.

**Comment by jliddev** [comment] 2020-12-29 20:08
Can someone test this on the latest beta and get back to me?

**Comment by mnejing** [comment] 2020-12-29 20:23
Just tested the beta12 portable executable. The old behavior where the client window would appear but couldn't be interacted with (until you right click in tray and selected Show) seems to be gone. However, issue 617 is now... err... an issue. The window sometimes resizes and the maximize button shows as restore size instead (the two overlapping boxes instead of a single box) and the window doesn't always respond correctly. 

It does, however, seem like you're on the right track. I think maybe you've figured this issue out, but issue 617 is now more obvious. Without looking at ANY of the code, I'd strongly suspect they're related.

**Comment by jliddev** [comment] 2020-12-29 21:58
I was never able to replicate this issue on my machine so its a little hard to fix. these two issues are both related to the reposition of the window works i assume. what are you doing to replicate this?

**Comment by jliddev** [comment] 2021-01-01 21:44
Made another change to the window stuff, give it a shot

**Comment by mnejing** [comment] 2021-01-02 04:34
It's back the old behavior. I'm again just using the portable version (2.1.0b15), because I don't want to overwrite my stable install. 

Specifically what I'm doing is this. I have 3 monitors at my desk, and my TV is also connected to it. I don't keep the TV on all the time, so when I turn it on, it causes Windows to redraw the desktop environment (at least, I believe it does). Anyway, if I have WowUp minimized to tray (which is basically always), when the redraw happens, the WowUp window restores it's position, but can't be interacted with. It just appears on screen in some previous state. I can't resize the window, click any buttons, anything. However, if I right click the icon is the system tray and select "Show," the client properly draws the window and works again. 

The reason this bothered me in the first place was because I didn't realize that using the tray icon and selecting Show "fixed" the problem and ultimately I kept force closing it through Task Manager. That was annoying to deal with any time I either wanted that monitor back or wanted to use the client. The workaround is simple, but it's not necessarily obvious. 

Ultimately it's a very minor inconvenience (oh no, I have to right click the tray!), it's just odd behavior.

**Comment by jliddev** [comment] 2021-01-02 05:31
I guess im confused, if you keep it minimized to tray, how is the window appearing and not responding without clicking the tray icon?

**Comment by jliddev** [comment] 2021-01-04 17:04
I tried all manner of unplugging and switching monitors and am unable to reproduce.

**Comment by thettenhausen** [comment] 2021-01-04 17:33
I installed beta 16 and will watch it a bit. I had it set to really close on close now, because it was a bit annyoing with the buggy behavior. have set it to minimize now again.
I have a setup where I have two monitors, one is connected via HDMI to two computers with a switch, and one is connected to one computer via DVI, and the other via HDMI, and I toggle it via the source selector on the monitor itself. Computerss are work and gaming. I had the bug happen when coming back to gaming after work, so all computers were up a while and had gone to sleep automatically. Will see if this recreates the bug for now with beta 16 running in the background.

**Comment by jliddev** [comment] 2021-01-08 00:47
If someone is able to replicate this a video or something might help. I've tried all kinds of unplugging of monitors with no luck.

**Comment by thettenhausen** [comment] 2021-01-12 16:23
I cannot replicate the problem anymore, looks fine for me now.

**Closed** 2021-01-26 18:59 UTC
Labels: bug
