### ISSUE TITLE
No check if a new addon version even supports the installed WoW version

### ISSUE THREAD

**Issue by Myrthian** [WowUp/WowUp#591] opened 2020-12-13 09:33 UTC
- Only have WoW retail installed
- Use an addon like e.g. [Tinypad](https://www.curseforge.com/wow/addons/tinypad/files) where the newest addon version only supports classic, but not retail -> WoWUp wants to update to the newest version which only supports classic, even though only retail is installed -> **Bug**
- [Screenshot](https://i.imgur.com/T2lvilp.png)

Expected:
- A check if the latest addon version even supports the currently installed WoW version: if it doesn't then only the latest addon version supporting the currently installed WoW version is displayed as an update, which in the case of Tinypad would be to offer 3.0.5 as an update for WoW retail, and not like currently 3.0.6 for classic

**Comment by linaori** [comment] 2020-12-13 09:46
Seems like the addon is not configured properly on curse. You can check the API call made here: https://addons-ecs.forgesvc.net/api/v2/addon/84962/

For the latest file you'll see:
```
gameVersion: {0: "8.3.0", 1: "1.13.5"}
gameVersionFlavor: "wow_retail"
```

Curse is presenting this addon as a retail addon, so there's not much we can do on the wowup side.

**Comment by Myrthian** [comment] 2020-12-13 09:52
As my understanding of code if just above 0: the issue seems to be that the addon has 2 game version + the first version is the classic one, right?

**Comment by linaori** [comment] 2020-12-13 09:56
That's 1 issue afaik, and the other is that it's explicitly marked as "wow_retail" while it should be "wow_classic"

**Comment by jliddev** [comment] 2020-12-13 15:56
Im not sure i understand that the issue is , the author has listed that 3.0.6 is the latest for both classic and retail.

![image](https://user-images.githubusercontent.com/20467484/102016966-73c25080-3d29-11eb-8f5e-1187584f04f6.png)

**Comment by Myrthian** [comment] 2020-12-13 20:37
I took another look.
On Curse the addon is indeed listed as supporting both retail and classic:
![01](https://user-images.githubusercontent.com/30933093/102023009-def03f00-3d8a-11eb-9f46-08304a9c53b7.png)

In WoWUp I can see only classic as supported game version, and not retail:
![00](https://user-images.githubusercontent.com/30933093/102023041-119a3780-3d8b-11eb-90d1-bf4890aa0d92.png)

**Comment by linaori** [comment] 2020-12-13 22:09
It shows up for retail when I search for it
![image](https://user-images.githubusercontent.com/1754678/102025436-38129f80-3d98-11eb-80c1-53068c67b5c5.png)

**Comment by jliddev** [comment] 2020-12-14 17:23
This is working as intended for now, curse says the addons is for wow_retail so that's what it appears valid with.
See #306 for further discussion.

**Closed by jliddev** 2020-12-14 17:23 UTC
