### ISSUE TITLE
Add changelog notes for addons

### ISSUE THREAD

**Issue by panoplybez** [WowUp/WowUp#93] opened 2020-10-03 21:44 UTC
Is it possible to add the changelog for addons when they are updated somehow? Not sure how feasible it is, but right now you click the addon name to go to the project side, then check under Files to look for update notes. Maybe like a tooltip on latest version or something? Unsure how best to accomplish.

**Comment by Daeveren** [comment] 2020-10-04 07:56
Definatelly a must have feature. It's the biggest thing I'm missing now that I've switched to Wowup.

**Comment by jliddev** [comment] 2020-11-29 04:41
Duplicate of #54

**Closed by jliddev** 2020-11-29 04:41 UTC
Labels: enhancement
