### ISSUE TITLE
Re-Scan folders breaks monitoring of addons installed via 'Install from URL'

### ISSUE THREAD

**Issue by alphabitnz** [WowUp/WowUp#1140] opened 2022-03-01 03:07 UTC
Fairly self explanatory, 
Re-Scan folders breaks monitoring of addons installed via 'Install from URL'

To reproduce:
1. Install an addon from a github URL source (e.g. TipTac - https://github.com/frozn/TipTac/)
2. Do a Re-Scan Folders
3. The addon now shows 'Ignored' - "The installed addon did not match with any of the configured providers"

Temporary workaround is to re-do the 'Install from URL' feature for every addon this breaks every time you Re-Scan, which is understandably not ideal.

**Comment by jliddev** [comment] 2022-03-02 04:39
Dupe of #463

**Closed by jliddev** 2022-03-02 04:39 UTC
