### ISSUE TITLE
Option to delete addon configuration

### ISSUE THREAD

**Issue by haruharu1** [WowUp/WowUp#616] opened 2020-12-27 00:15 UTC
**Is your feature request related to a problem? Please describe.**
Having the option when uninstalling addons to have the option to delete the configuration (saved variables) together.

**Describe the solution you'd like**
 Via checkbox or configuration.

**Additional context**
Sometimes if an addon bugs out and you want to do a clean install having this option would help a lot.

**Comment by jliddev** [comment] 2020-12-27 15:29
Duplicate of #535

**Closed by jliddev** 2020-12-27 15:29 UTC
