### ISSUE TITLE
Re-install all

### ISSUE THREAD

**Issue by cvarjao** [WowUp/WowUp#589] opened 2020-12-11 22:45 UTC
**Is your feature request related to a problem? Please describe.**
I like to keep my wow settings (including addons) backed-up and synchronized across multiple computers. I've added WowUp settings to my backup (3 files from the userdata folder specifically: `addons.json`, `Preferences`, and `preferences.json`). Which works fine, the only problem is that I need to manually go to each addon and then re-install them. there isn't not even an option to select all addons (ctrl + a), right click, and then `re-install`

**Describe the solution you'd like**
I understand that it might not be an use case WowUp had in mind, but if you could add a `re-install all`  (analogous to `update all`) it would already be really helpful.

**Describe alternatives you've considered**
manually go to each addon and right lick and then click `re-install`

**Additional context**
This is really for the the use case of backup and restore wow settings. I could just keep backing up the whole addons folder, but that is getting big (specially as I am using a git repository to keep in version control, and I can go back when I made an error configuring addons/UI)

Thank you very much for this amazing tool!

**Comment by jliddev** [comment] 2020-12-27 15:33
We'll get there, dupe of #482

**Closed by jliddev** 2020-12-27 15:33 UTC
