### ISSUE TITLE
Hard-to-see button on the "WowUp Update Ready" Screen with the Dark Horde theme

### ISSUE THREAD

**Issue by danzy** [WowUp/WowUp#556] opened 2020-11-29 21:05 UTC
**Describe the bug**
Using the Dark Horde Theme, on the "WowUp Update Ready" screen (that prompts the user to restart WowUp and install the update), the No button is very difficult to see, almost invisible.

**To Reproduce**
1. Perform an update within the WowUp application
2. Be prompted to restart Wowup and install the update

**Expected behavior**
The 'no' button to be more visible than it currently is.

**Screenshots**
![wowup-update-ready](https://user-images.githubusercontent.com/5334491/100553568-6f585b00-3286-11eb-8c74-32e436f7fce1.png)
If it helps, imgur link: https://imgur.com/wi8RYIE

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] N/A - I am using the application
 - Version [e.g. 22] v2.0.0, unsure if it is in v2.0.1 but judging from the changenotes in v2.0.1 it may be present there as well.

**Comment by danzy** [comment] 2020-11-29 21:06
If it helps, it appears the Dark Alliance theme has a similar problem:

![image](https://user-images.githubusercontent.com/5334491/100553618-b6465080-3286-11eb-81b4-45d7b2ac6daa.png)

**Comment by linaori** [comment] 2020-11-30 11:02
Closing this as a duplicate of #520. There might be some more places where this issue appears, and all comes down to the generic styling

**Closed by linaori** 2020-11-30 11:02 UTC
Labels: bug, duplicate
