### ISSUE TITLE
Windows 7 Support Dropped in 2.9.4

### ISSUE THREAD

**Issue by Ketrel** [WowUp/WowUp#1441] opened 2023-06-04 22:34 UTC
**Describe the bug**
It appears 2.9.4 no longer supports Windows 7
It crashes out with an error

**To Reproduce**
1. Install and try to run on Windows 7

**Screenshots**
![csrss_2023-06-04_18-33-26](https://github.com/WowUp/WowUp/assets/1002607/77ad8bc2-f591-47e4-ac25-0f0cf3473b52)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: n/a
 - Version 2.9.4

**Additional context**
I run wow on an older machine, and Wowup updated itself, and installing 2.9.3 just makes me re-update.

**Comment by linaori** [comment] 2023-06-04 22:38
Windows 7 support has ended for a while, not much that can be done about this.

**Comment by Ketrel** [comment] 2023-06-04 22:59
It would have been nice to know this was coming.  It just updated and broke itself.  Now there's no way to update addons on that machine other than manually.

I'm building a new gaming machine (Linux based this time) but it's not something soon, so it was kind of a yanking the carpet out from under without warning.

**Comment by linaori** [comment] 2023-06-05 09:00
Regardless the outcome wouldn't have changed, the app will update itself and it would've broken anyway. If you have a way to prevent that from happening you can still download the old version from github, but then certain features won't work.

We have no control over what electron supports, and based on how long ago Windows 7 support has been dropped, I'm surprised it still worked in the first place. I'm not 100% sure what decides the build version for electron, but I'm assuming it just grabs the latest. 

> May 30 2023: Electron 22 reaches the end of its support cycle.
> https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

To bridge the gap you can also manually build an older version of the app locally, you'll just have to manually get the tukui changes in if you use ElvUI or TukUI.

**Comment by Ketrel** [comment] 2023-06-05 13:28
That's exactly what I can't do.

Old versions seems tonblank out the whole app and say there's a newer version and there's no way to dismiss the overlay.

I tried an older version as the very first thing.

Unless I also modify the update code, I don't see how building would help either in this case for the same reason.

Honestly I was hoping support for Win 7 for addon clients would last as long as Blizz's support for Win 7, but either way some notice that this version is a breaking one before it hit would have been nice.

(Next gaming machine is Linux so I will have WINE issues, but will be able to whatever version.)


On June 5, 2023 5:00:24 AM EDT, Lynn ***@***.***> wrote:
>Regardless the outcome wouldn't have changed, the app will update
>itself and it would've broken anyway. If you have a way to prevent that
>from happening you can still download the old version from github, but
>then certain features won't work.
>
>We have no control over what electron supports, and based on how long
>ago Windows 7 support has been dropped, I'm surprised it still worked
>in the first place. I'm not 100% sure what decides the build version
>for electron, but I'm assuming it just grabs the latest. 
>
>> May 30 2023: Electron 22 reaches the end of its support cycle.
>> https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice
>
>To bridge the gap you can also manually build an older version of the
>app locally, you'll just have to manually get the tukui changes in if
>you use ElvUI or TukUI.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/WowUp/WowUp/issues/1441#issuecomment-1576405149
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by linaori** [comment] 2023-06-05 13:43
> Unless I also modify the update code, I don't see how building would help either in this case for the same reason. 

You'll have to build it locally with an older version. If this triggers an update, you can manually change the version I think (I haven't tried this myself).

> Honestly I was hoping support for Win 7 for addon clients would last as long as Blizz's support for Win 7

Maybe another app can do it? I don't think people will go out of their way to support Windows 7, but it might be worth trying depending on how long it'll take for you to get a new OS.

> either way some notice that this version is a breaking one before it hit would have been nice.

I'm pretty sure that nobody considered that this would be a breaking change, and going through all the dependencies manually is kind of a pain. Besides of that we have no infrastructure to announce these kind of changes either, so it would've cost a lot of time to build that while people were unable to update their ElvUI.

It's unfortunate that this doesn't work for the handful of Windows 7 users, but there's nothing that could've realistically been done to prevent it from happening or notify in the first place.

**Comment by bish0polis** [comment] 2023-06-12 04:40
> Windows 7 support has ended for a while, not much that can be done about this.

Quick thoughts, ignoring the comma splice above:

1. don't do the thing that makes the app crash on it.
2. don't allow updates past where support has been summarily dropped 
    a. on a POINT RELEASE ?!?
4. allow rollbacks when the new version fails validation (running)
5. actually include some post-patch validation, I guess too

Wow.  That's 4 options worth of 'not much that can be done' in about 10 seconds of thought, and the first two are junior stuff.

**Comment by linaori** [comment] 2023-06-12 08:00
> Wow. That's 4 6 options worth of 'not much that can be done' in about 10 20 seconds of thought, and the first two are junior stuff.

Exactly, junior stuff, and also the reason why they are not senior. 

> don't do the thing that makes the app crash on it.

Like I mentioned before, that's Electron, and an unmaintained version thereof. 

> don't allow updates past where support has been summarily dropped

Sure, possible. Make a feature request and hope someone picks it up.

> on a POINT RELEASE ?!?

Applications do not follow semver, this only makes sense for libraries.

> stop automatically updating your users into a preventable trap

The result is that users won't update, and report broken things that are already fixed. There's a reason it's a forced update. That said there was an attempt in the previous beta to add a snooze button, but due to lack of development time it wasn't continued. Feel free to pick it up.

> 4. allow rollbacks when the new version fails validation (running)
> 5. actually include some post-patch validation, I guess too
> 6. offer a solution for installing the tool without the 'update to unusable' trapdoor

Make a ticket or PR

If it's so easy, you should be able to do it.

**Comment by linaori** [comment] 2023-06-12 15:24
Look I'm going to sum it up for you in case the hint wasn't clear in my previous reply: The app is free to use. You can request features, but there's no guarantee they will be made. If you wish to contribute, you're free to do so. If all you do is complain that my answers aren't up to your standards and you disagree with them for some arbitrary reason, then I can't help you here.

You can either contribute the features on your own, make an issue requesting certain features, or pay if you want someone to make time for you and implement it.

If non of these options work for you I'm sure there's another tool you can use.

**Comment by Ketrel** [comment] 2023-06-12 15:26
Look, I don't want to get involved in anynof this, but at least be honest.

"Applications do not follow semver, this only makes sense for libraries."

Is a lie. Not only is it a lie, but this is an add-on client for World of Warcraft, an application that follows semver.

On June 12, 2023 4:00:21 AM EDT, Lynn ***@***.***> wrote:
>> Wow. That's 4 6 options worth of 'not much that can be done' in about
>10 20 seconds of thought, and the first two are junior stuff.
>
>Exactly, junior stuff, and also the reason why they are not senior. 
>
>> don't do the thing that makes the app crash on it.
>
>Like I mentioned before, that's Electron, and an unmaintained version
>thereof. 
>
>> don't allow updates past where support has been summarily dropped
>
>Sure, possible. Make a feature request and hope someone picks it up.
>
>> on a POINT RELEASE ?!?
>
>Applications do not follow semver, this only makes sense for libraries.
>
>> stop automatically updating your users into a preventable trap
>
>The result is that users won't update, and report broken things that
>are already fixed. There's a reason it's a forced update. That said
>there was an attempt in the previous beta to add a snooze button, but
>due to lack of development time it wasn't continued. Feel free to pick
>it up.
>
>> 4. allow rollbacks when the new version fails validation (running)
>> 5. actually include some post-patch validation, I guess too
>> 6. offer a solution for installing the tool without the 'update to
>unusable' trapdoor
>
>Make a ticket or PR
>
>If it's so easy, you should be able to do it.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/WowUp/WowUp/issues/1441#issuecomment-1586788837
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Ketrel** [comment] 2023-06-12 17:16
You're talking the WoW API. I was referring to the game.  Major = expansion, Minor = content, Patch = patch.

That's what they follow.

On June 12, 2023 11:37:06 AM EDT, Lynn ***@***.***> wrote:
>I'm not sure you understand what semver is.
>
>> Summary
>> Given a version number MAJOR.MINOR.PATCH, increment the:
>> 
>> MAJOR version when you make incompatible API changes
>> MINOR version when you add functionality in a backward compatible
>manner
>> PATCH version when you make backward compatible bug fixes
>> Additional labels for pre-release and build metadata are available as
>extensions to the MAJOR.MINOR.PATCH format.
>> - https://semver.org
>
>According to "Semantic Versioning Specification" the WowUp app itself
>does not provide a public API. Applications such as Google Chrome don't
>use it either, as it simply does not make sense for applications. I'd
>argue that if an application wants to use semver-like versioning
>despite it making no sense, that's up to them.
>
>If you really want to go into the details, WoW does not follow semver
>either. If we take a look at the only public API that WoW provides (the
>Lua API), there are breaking changes in patches:
>https://wowpedia.fandom.com/wiki/Patch_10.0.7/API_changes
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/WowUp/WowUp/issues/1441#issuecomment-1587584887
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by linaori** [comment] 2023-06-12 17:31
They just follow a certain 3 number versioning, that doesn't make it semver.

**Comment by MrUzagi** [comment] 2023-06-13 00:18
Most things work right up until they don't. Sometimes we might even know about it in advance, sometimes not.

But I guess I just don't get why it's such a big deal in the first place. 

And I've never claimed to be a professional anything. Mediator least of all. 🙃

**Comment by Ketrel** [comment] 2023-10-03 13:12
I think this can be closed.  
In the interim, I ran wowup in a Linux VM on the Windows 7 machine and had the addons folder shared with the VM.  Hackesh, but worked.

Then in August my windows 7 machine kicked it, and I'm full Linux now in which wowup works just fine.

**Comment by Rhea-3** [comment] 2023-10-13 23:37
A bit late, but for others who came across:
You can also use supermium-electron to run WoWUp on Win7, seems to work fine =)
https://github.com/win32ss/supermium-electron
For now, you dont even have to build, you can just dl latest release there (dist_x64.zip) and copy the contents of the "resources" folder from latest WowUp.exe (app.asar and app.asar.unpacked folder) inside the resources folder of the supermium electron release et voilà.
(Tested with WowUp 2.10 and supermium-electron 28)

**Comment by nb41** [comment] 2023-11-24 22:11
Also a bit late, but, I can confirm Rhea-3's solution still works fine. 
1. Download the current supreium-electron tagged release (dist_x64.zip), unzip it into a folder.
2. Install WoWUp. 
3. From the WoWUp install folder (`C:\Users\USER_NAME\AppData\Local\Programs\wowup\resources` on my mahcine) copy `app.asar` and `app.asar.unpacked` into the supremium-electron `resources` folder.
4. Launch electron.exe from the root supremium-eletron folder. As Rhea-3 says, voila. A workaround for those of us still on Win7 for some machines.

**Comment by bish0polis** [comment] 2024-08-14 07:08
> Good grief. Windows 7 reached end of life [over three years ago](https://learn.microsoft.com/en-us/lifecycle/products/windows-7). Mainstream

Absolutely orthogonal to the problem at hand. 

> The app is free to use. 

Maintaining or donating code to various open-source projects for about 2 decades and I didn't need to rock out 'the app is free' since no one asked that question; and I'm confused why it relates to a bad merge now.  But obviously it's a language barrier, and that's okay.

Good luck.  Ideally I can build something you can use one day.

**Comment by linaori** [comment] 2024-08-14 07:23
@bish0polis "The app is free" is most certainly an important part of it, nobody is paying for development time to keep maintaining old software. Anyhow I'm going to close this issue because it's pointless. Electron moves on and so does WowUp.

**Closed by linaori** 2024-08-14 07:23 UTC
