### ISSUE TITLE
[2.x] Make Show Folder show a list of all folders created by addon

### ISSUE THREAD

**Issue by stevietv** [WowUp/WowUp#284] opened 2020-10-31 08:55 UTC
As in the twitch client, Show Folder showed a sublist of all folders that had been created by this addon.
this can be useful when addons install many folders (eg DBM, Altoholic)

**Comment by linaori** [comment] 2020-10-31 09:11
There is something like this in drafts I believe, so perhaps soon ™️ ? 😄 

_Possible duplicate of #251_

**Comment by jliddev** [comment] 2020-11-01 16:34
Seems like an enhancement to the existing show folders, if multiple folders show this dropdown?

**Closed** 2020-12-29 20:08 UTC
Labels: enhancement
