### ISSUE TITLE
[2.x Feature Request] Remember Column Sort

### ISSUE THREAD

**Issue by Evolutious** [WowUp/WowUp#316] opened 2020-11-03 19:03 UTC
Just requesting that it be added into the 2.0 client to save when you sort by a certain column so that it retains that sort even through a client restart. thanks!

**Comment by jliddev** [comment] 2020-11-04 16:57
We need to re-work storing columns all together, should allow defaulting a column to off which is not currently possible

**Comment by panoplybez** [comment] 2020-11-09 00:38
Just downloaded beta version .6 and still doesn't seem to be saving column sort direction between sessions.

**Comment by Evolutious** [comment] 2020-11-09 01:21
> Just downloaded beta version .6 and still doesn't seem to be saving column sort direction between sessions.

Are you sure it isnt saving or is it that the column that you are selecting to sort is being saved but it is resetting that column to sorting with an up arrow? Because that is the issue I am seeing. I can sort by any column but it will change the sort to being an up arrow on restart.

**Comment by panoplybez** [comment] 2020-11-09 01:29
I had opened a ticket about this the other day, but it was marked a duplicate of this. You're right, what is not saving is the direction of sorting. The column sorted on IS saved, but the direction (up or down arrow) is not.

**Comment by Evolutious** [comment] 2020-11-09 01:33
This gets pushed to the WowUp Discord, so I am certain that @jliddev will see this and investigate ;)

**Comment by panoplybez** [comment] 2020-11-09 01:39
Sounds good! thank you. :D

**Comment by jliddev** [comment] 2020-11-09 17:41
Give this a shot in the latest beta 7

**Comment by panoplybez** [comment] 2020-11-09 17:57
So with beta 7 it appears to be working, mostly! It did save in between sessions (yay), but I've noticed that hitting the 'Check Updates' button makes it start toggling between like, all possible options for the column. I have it sorted descending, I hit Check Updates, it comes back now ascending - I hit 'Check Updates' again, now its not showing sorted at all. I hit Check Updates again, now its back to descending, except that the arrow is now pointed in the wrong direction. =D

**Comment by jliddev** [comment] 2020-11-09 19:54
Ok give beta 8 a try, seems to be working better

**Comment by panoplybez** [comment] 2020-11-09 20:07
beta 8 is working! Column direction is saved, and checking updates doesn't change it anymore. thanks so much!

**Closed** 2020-11-09 20:31 UTC
Labels: enhancement
