### ISSUE TITLE
'View on Curse'  in right click menu.

### ISSUE THREAD

**Issue by stevietv** [WowUp/WowUp#446] opened 2020-11-17 22:22 UTC
**Is your feature request related to a problem? Please describe.**
If i want to view the changelog of an addon I first click the addon to get the dialog showing the info, then click the view on curse, and finally close the intermediate dialog window

**Describe the solution you'd like**
add "view on curse" to the right click menu.
This would streamline the method to access the website

**Describe alternatives you've considered**
alternatively, the external link icon could be added tot he provider column or another column on the addon list

**Additional context**
none

**Comment by Zazou89** [comment] 2020-11-18 21:57
From @Linaori : 
> This feature is very much wanted and will be worked on as soon as there's some time

Duplicate of #93,#54 and #430

**Comment by stevietv** [comment] 2020-11-18 22:01
Nice to know, however I do think that my request is a little different to the duplicates that specifically ask for change-log where as I'm looking for a quicker link to the curse page.

**Comment by jliddev** [comment] 2020-11-18 22:17
Clicking the name then the link is the same number of clicks as right clicking and then the link. Someone can make a PR for it if they like.

**Comment by stevietv** [comment] 2020-11-18 22:22
I agree that it's the same number of clicks. But then an extra click is
also needed to close the interim dialog box also. Further its quite some
cursor movement over three different parts of the screen versus all in a
concentrated area.

Hope that someone would decide to pick up this as a PR!

**Closed** 2020-12-30 17:12 UTC
Labels: enhancement, help wanted
