### ISSUE TITLE
Curse is not returning this addon as expected

### ISSUE THREAD

**Issue by Dukeenrike** [WowUp/WowUp#1214] opened 2022-05-08 01:12 UTC
**Describe the bug**
Starting on 05/07/2022 several addons return this warning : 

Curse is not returning this addon as expected

**To Reproduce**
1.Open WowUp
2. Click on check for updates
3. See error on a few addons : 

a) Auctionator 9.2.15
b)Details Damage Meter 9.2.0.9780.146
c)HandyNotes: Shadowlands v46

**Expected behavior**
Should be able to update

**Screenshots**
https://ibb.co/DQjnHzP

**Comment by tomrus88** [comment] 2022-05-08 03:12
I have same issue with exact same addons.

**Comment by zerogott** [comment] 2022-05-08 07:04
https://wowup.io/guide/wowup/curseforge-migration
Seems like it has todo with this.

**Comment by Mr-nUUb** [comment] 2022-05-09 16:16
> https://wowup.io/guide/wowup/curseforge-migration Seems like it has todo with this.

I don't think so:
* all addons from Curse would be affected, but it's limited to a small number
* the issue is gone after updating WowUp to v2.7.1

**Comment by jliddev** [comment] 2022-05-11 03:45
The CF API was having issues for a few days. This may have resolved itself.

**Comment by linaori** [comment] 2022-05-26 12:01
Closing this issue as curse is no longer accessible

**Closed by linaori** 2022-05-26 12:01 UTC
