### ISSUE TITLE
Downgrade Version Within Right-Click Menu

### ISSUE THREAD

**Issue by JohnnyGrey86** [WowUp/WowUp#1021] opened 2021-09-26 22:19 UTC
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
A "Previous Version..." right-click menu item with a sub-menu containing previous version numbers.

**Describe alternatives you've considered**
Not considered any.

**Additional context**
No additional context needed.

**Comment by jliddev** [comment] 2021-11-08 20:18
Duplicate of #16

**Closed by jliddev** 2021-11-08 20:18 UTC
