### ISSUE TITLE
Addon versions not being correctly recognized after a re-scan.

### ISSUE THREAD

**Issue by CMcFadyen** [WowUp/WowUp#435] opened 2020-11-17 01:13 UTC
Every time I do a re-scan of my addons, WowUp thinks it needs to update a bunch of addons that are already up to date.  https://www.wowinterface.com/downloads/info11205 is one, DBM, and some HandyNotes plug-ins are among the others.

Log file from the re-scan is attached (same log file as the other bug report I just filed).
[wowup-logs20201116.txt](https://github.com/WowUp/WowUp/files/5550622/wowup-logs20201116.txt)

**Comment by Nuvelle** [comment] 2020-11-17 17:33
I can confirm DBM is doing the same.

Clean install.

My version shows as 9.0.3 with latest being 9.0.4.

 An update updates my version to 9.0.4 but a re-scan resets it to 9.0.3.

Checking DBM-Core.toc shows version 9.0.4.

**Comment by jliddev** [comment] 2020-11-17 17:37
our fingerprint server is on a 3 hour delay since the curseforge one does not work properly which would only affect you during a rescan.

**Comment by jliddev** [comment] 2020-11-17 17:38
A rescan is unnecessary unless you're updating addons outside of WowUp for what it's worth

**Comment by CMcFadyen** [comment] 2020-11-17 17:46
That's exactly why I've been re-scanning, between a bunch of addons not being recognized or WowUp forgetting ones it previously found.

**Comment by jliddev** [comment] 2020-11-17 17:51
It is possible that your issues are fixed in the latest beta as it is more advanced that the 1.x client

**Comment by CMcFadyen** [comment] 2020-11-17 17:59
After installing the 2.0 beta, it's asking me to update all the ones I mentioned in the original ticket that are already up to date: https://i.imgur.com/64c7Q0b.png

Also, Auditor is maintained at curseforge now (https://www.curseforge.com/wow/addons/auditor), but it's still finding the 10 year old version on wowinterface.

**Comment by jliddev** [comment] 2020-11-17 18:12
the DBM version is because of the delay like above, id have to look at your auditor toc to see why that might be happening

**Comment by jliddev** [comment] 2020-11-17 18:14
Feel free to send your renderer.log and we can dig deeper

**Comment by CMcFadyen** [comment] 2020-11-17 18:16
Auditor might be because the folder is now Auditor3?  Here's the toc:

[Auditor3.zip](https://github.com/WowUp/WowUp/files/5555403/Auditor3.zip)

And the log:
[renderer.log](https://github.com/WowUp/WowUp/files/5555405/renderer.log)

**Comment by jliddev** [comment] 2020-11-17 18:47
So something is up with your Auditor3 install , curse wont detect it via fingerprint either, you can install it fresh from the get addons tab to fix it.

Curse returns the same versions for your handynotes fingerprints that we're showing as well so everything seems to be working correctly as far as i can tell.

**Comment by CMcFadyen** [comment] 2020-11-17 19:17
I probably edited Auditor to fix 9.0 bugs that haven't been fixed by the author.  I do that with every broken addon.  Can WowUp not detect modified addons so that when the author fixes them they can be updated?

**Comment by jliddev** [comment] 2020-11-17 19:20
Thats a complicated question, modified relative to what? if the addon only exists on CF then yeah sure we can detect changes. but since it also lists a WowI ID wowI tells us nothing about that folder so all we can do is say well, it has an ID it must be this addon.

**Comment by CMcFadyen** [comment] 2020-11-17 19:28
Interesting conundrum.  That's good to hear though, that it won't be something that happens with the vast majority of addons.

**Closed** 2020-11-18 22:15 UTC
